# Base URL para im\u00e1genes en desarrollo
procol.url.base-imagenes=http://localhost:3210

app.base-url=http://localhost:3210

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/db_procol
spring.datasource.username=user_procol
spring.datasource.password=123456
# Rutas locales
procol.ruta.imagenes=C:/procol/imagenes
procol.ruta.imagenes-vacantes=C:/procol/imagenes/vacantes
procol.ruta.documentos=C:/procol/documentos
