# Base URL para im\u00e1genes en producci\u00f3n
procol.url.base-imagenes=https://propocol.backcoreunimag.com

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://86.48.22.245:5432/db_procol
spring.datasource.username=user_procol
spring.datasource.password=45c70efa817ffe154a7fd9056690e46111b76b5fb3cb7403013298d9a62a7232

# Rutas servidor
procol.ruta.imagenes=/var/procol/imagenes
procol.ruta.imagenes-vacantes=/var/procol/imagenes/vacantes
procol.ruta.documentos=/var/procol/documentos
