spring.application.name=propositosColombia

# Configuraci\u00f3n de JPA y Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none

# Logging detallado
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.transaction=TRACE

# Configuraci\u00f3n del servidor
server.port=3210
server.servlet.context-path=/
spring.mvc.throw-exception-if-no-handler-found=true
server.error.whitelabel.enabled=false
server.error.include-message=always

# JSON
spring.jackson.deserialization.fail-on-unknown-properties=true

 # Carga de archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# Perfiles activos
# \u00f0\u009f\u009f\u00a2 DESARROLLO: Seguridad activada (WebSocket valida token en STOMP CONNECT)
spring.profiles.active=dev,security-enabled
# spring.profiles.active=prod,security-enabled


# Configuraci\u00f3n de SMS
hablame.api.url=https://www.hablame.co/api/sms/v5/send
hablame.api.key=AQKq03JaKw6jm0WJFzHnrr1TEeojqlCstAxzP1fgHGVZbmNNdiJR7p4dthgL4g8QDQA66nWuSYZM9nwUOIet5zE2kTuN7BcBM3j3Ua9Gbd0xhokRXawyOqXDM9GDvTmW


# Configuraci\u00f3n del servidor de correo:
app.mail.from-name=Notificaciones Swallow
spring.mail.host=mail.msgcoreunimag.com
spring.mail.port=587
spring.mail.username=correo@msgcoreunimag.com
spring.mail.password=0ec9c4f92f6c92b96ffcb8f2b85373befc2b37f849d675ec0a834d268ed81eaafd3be0a81fc7f7c0d18449d309a4d3b9b62787ab9966a93f624246ccc73235db
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Solo exponer la carpeta de vacantes
spring.web.resources.static-locations=file:${procol.ruta.imagenes-vacantes}/